# Aprendizagem Computacional - Projeto 01
# Regressão aplicada à esperança média de vida
## Alix Carmo nº23324 & Vasco Araújo nº23049

In [62]:
# import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from itertools import combinations

In [51]:
df = pd.read_csv("./datasets/Life Expectancy Data.csv")
#df.head(9)

df.head(9)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,...,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,...,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,...,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,82,0.02,10.910156,63.0,1141,...,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4

## Transformação dos dados

In [ ]:
#transformação dos paises em valores númericos
label_encoder = preprocessing.LabelEncoder()
df['Country'] = label_encoder.fit_transform(df['Country'])

#transformação dos estados de desenvolvimento em valores númericos
numeric_var = {'Status': {'Developing':1, 'Developed':2}} 
df = df.replace(numeric_var)

#replace all empty values with 0
df.fillna(0, inplace=True)

df.head(9)

## Simple Linear Regression

In [56]:
def my_regression_function(datax, datay):
    # Convert to numpy arrays
    X = datax.values.reshape(-1, 1)
    y = datay.values.reshape(-1, 1)

    # Split the data into training and test sets
    train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.2)

    # Train a linear regression model
    regr = linear_model.LinearRegression()
    regr.fit(train_x, train_y)

    # Output the coefficients
    print('Coefficients:', regr.coef_[0][0])
    print('Intercept:', regr.intercept_[0])

    # Predictions on the test data
    test_y_pred = regr.predict(test_x)

    # Calculate RMSE and r2
    rmse = mean_squared_error(test_y, test_y_pred, squared=False)
    r2 = r2_score(test_y, test_y_pred)

    # Output RMSE and R^2
    print(f'RMSE: {rmse}')
    print(f'R^2: {r2}')
    
    # Visualize the results
    '''
    plt.scatter(test_x, test_y, color='blue')
    plt.plot(test_x, test_y_pred, '-r', linewidth=3)
    plt.xlabel(label_axis_x)
    plt.ylabel(label_axis_y)
    plt.title(f'Linear Regression - {label_axis_x}')
    plt.show()'
    
    '''

In [54]:
# Find the index of 'Life expectancy' column
Adult_Mortality_index = df.columns.get_loc('Adult Mortality')

# Use .iloc to slice the DataFrame from the 'Life expectancy' column index to the end
cdf = df.iloc[:, Adult_Mortality_index:]

cdf.head(9)

,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,279.0,74,0.01,79.679367,66.0,1989,16.7,102,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,281.0,77,0.01,56.762217,63.0,2861,16.2,106,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,287.0,80,0.03,25.873925,64.0,1599,15.7,110,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,295.0,82,0.02,10.910156,63.0,1141,15.2,113,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4

In [59]:
target = df[['Life expectancy ']]
for i in cdf.columns:
    print(i)
    my_regression_function(cdf[[i]], target)
    print('\n')

Adult Mortality
Coefficients: -0.051130458964811706
Intercept: 77.41289168900752
RMSE: 9.161704366108742
R^2: 0.3040980503055294


infant deaths
Coefficients: -0.014437244503962292
Intercept: 69.40727571056537
RMSE: 9.794615331643318
R^2: 0.04600089366611626


Alcohol
Coefficients: 0.8948346956460057
Intercept: 65.27264862735193
RMSE: 9.552795105533702
R^2: 0.1392212475813811


percentage expenditure
Coefficients: 0.001883649388831204
Intercept: 67.69368052754862
RMSE: 9.343179364169437
R^2: 0.15323357083426625


Hepatitis B
Coefficients: 0.06202792647568764
Intercept: 64.86552060049658
RMSE: 9.91392779336617
R^2: 0.02667710037189852


Measles
Coefficients: -0.00011743312431235616
Intercept: 69.32551305800587
RMSE: 10.398549568859062
R^2: 0.02380942427639654


 BMI
Coefficients: 0.25463988082529904
Intercept: 59.205895266213346
RMSE: 7.409967895824389
R^2: 0.3486704258565796


under-five deaths
Coefficients: -0.013196733007804598
Intercept: 69.42608137887657
RMSE: 9.868551204681443
R^2: 0.029601329281406907


Polio
Coefficients: 0.18105769915538789
Intercept: 53.94020647531627
RMSE: 8.137260953857108
R^2: 0.2367452891018369


Total expenditure
Coefficients: 0.4644672433995444
Intercept: 66.48621057234212
RMSE: 10.58720971078177
R^2: 0.02591502446874483


Diphtheria
Coefficients: 0.17919805436855504
Intercept: 54.361196857286856
RMSE: 9.025080555114492
R^2: 0.2526383304772283


 HIV/AIDS
Coefficients: -1.0150577693630274
Intercept: 70.78849948852445
RMSE: 9.591778605504684
R^2: 0.22015688446560167


GDP
Coefficients: 0.00030528605057308537
Intercept: 67.23380569505001
RMSE: 10.280382980340733
R^2: 0.14658628562142784


Population
Coefficients: -3.2766774087442453e-09
Intercept: 68.99409672705187
RMSE: 10.240729769666778
R^2: 0.0009565765693138051


 thinness  1-19 years
Coefficients: -0.9115207767614081
Intercept: 73.32992661225374
RMSE: 8.778136659192494
R^2: 0.19459700908978572


 thinness 5-9 years
Coefficients: -0.9391080902709257
Intercept: 73.52493116258354
RMSE: 10.32994275554815
R^2: 0.08954641469563684


Income composition of resources
Coefficients: 23.611106765740573
Intercept: 54.984669224407234
RMSE: 8.886924913690514
R^2: 0.3251958026663525


Schooling
Coefficients: 1.330645624968416
Intercept: 53.92664302453147
RMSE: 8.90079148389442
R^2: 0.3157298334630366

## Multiple Linear Regression

In [83]:
def my_multiple_regression_function(X,y):
    # Split the data into training and test sets
    train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.2)

    # Train a linear regression model
    regr = linear_model.LinearRegression()
    regr.fit(train_x, train_y)

    # Output the coefficients
    #print('Coefficients:', regr.coef_)
    #print('Intercept:', regr.intercept_)

    # Predictions on the test data
    test_y_pred = regr.predict(test_x)

    # Calculate RMSE and r2
    rmse = mean_squared_error(test_y, test_y_pred, squared=False)
    r2 = r2_score(test_y, test_y_pred)

    # Output RMSE and R^2
    #print(f'RMSE: {rmse}')
    #print(f'R^2: {r2}')
    
    # The visualization part is removed because it's not as useful for multiple dimensions
    # However, if you have specific pairs of features you want to plot, you can still create plots for those

    return regr, rmse, r2

In [84]:
cdf_col= cdf.columns
best_r2 = float('-inf')
best_rmse = float('inf')
best_combination_r2 = None
best_regr_model_r2 = None
best_combination_rmse = None
best_regr_model_rmse = None

# Iterate over all combinations of columns starting from 1 column to len(cdf_col) columns
for i in range(1, len(cdf_col) + 1):
    for combo in combinations(cdf_col, i):
        # Select the current combination of columns for X
        dx = cdf[list(combo)].values
        # Call the regression function with the current X and the target y
        regr, rmse, r2 = my_multiple_regression_function(dx, target)
        
        # Check if the current R^2 is the best one and update the best values and combination
        if r2 > best_r2 
            best_r2 = r      
            best_combination_r2 = combo
            best_regr_model_r2 = regr
        if rmse < best_rmse
            best_rmse = rmse
            best_combination_rmse = combo
            best_regr_model_rmse = regr
            
print(f"Melhor r2: {best_r2} com a combinação {best_combination_r2} e modelo de regressão {best_regr_model_r2}")
print(f"Melhor rmse: {best_rmse} com a combinação {best_combination_rmse} e modelo de regressão {best_regr_model_rmse}")